import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Providers from './providers'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter'
import { Locale, i18n } from '@/i18n.config'
import Header from '@/components/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export async function generateStaticParams() {
  return i18n.locales.map(locale => ({ lang: locale }))
}

export default async function RootLayout({
  children,
  params
}: {
  children: React.ReactNode
  params: Promise<{ lang: Locale }>
}) {
  const { lang } = await params
  return (
    <html lang={lang}>
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <Providers>
            <Header lang={lang} />
            <main>{children}</main>
          </Providers>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
