import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Providers from '@/providers/providers'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter'
import { Locale, i18n } from '@/i18n.config'
import Header from '@/components/Header/Header1'
import ResponsiveAppBar from '@/components/Header/Header'
import { ModalProvider } from '@/providers/ModalProvider'
import { getTranslation } from '@/lib/translations'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/app/api/auth/_options'
import {
  TranslationProvider,
  Translations
} from '@/providers/TranslationProvider'
import Footer from '@/components/footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Custom title',
  description: 'Generated by create next app'
}

export async function generateStaticParams() {
  return i18n.locales.map(locale => ({ lang: locale }))
}

export default async function RootLayout({
  children,
  params
}: {
  children: React.ReactNode
  params: Promise<{ lang: Locale }>
}) {
  const { lang } = await params
  const session = await getServerSession(authOptions)
  const translation = (await getTranslation(session, lang)) as Record<
    Locale,
    Translations
  >
  console.log('Layout translation', translation)
  return (
    <html lang={lang}>
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <Providers>
            <TranslationProvider translation={translation} locale={lang}>
              <ModalProvider>
                <ResponsiveAppBar lang={lang} />
                <main>{children}</main>
                <Footer />
              </ModalProvider>
            </TranslationProvider>
          </Providers>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
